### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by OrsonMM** [gpertea/cdbfasta#1]
Hi i use these command 

drisee.py -g ../../Programas/DRISEE/adapterDB.fna ../../Programas/DRISEE/example_fasta my_fasta.err

and obtain these error:

Traceback (most recent call last):
  File "/home/oamestanzam/Programas/DRISEE/drisee.py", line 601, in <module>
    sys.exit(main(sys.argv))
  File "/home/oamestanzam/Programas/DRISEE/drisee.py", line 580, in main
    write_file(summary, LOG_FILE, 1)
  File "/home/oamestanzam/Programas/DRISEE/drisee.py", line 75, in write_file
    outhdl = open(fname, mode)
TypeError: coercing to Unicode: need string or buffer, NoneType found

please, help

**Comment by gpertea** [comment]
Actually unrelated to cdbfasta. User seems to be mis-using github to cross-post random error message which suggests lack of understanding of the process..
